### ISSUE TITLE
1.19.4 crashing with a rendering issue everytime I open the disenchanter

### ISSUE THREAD

**Issue by Sourpunch14** [glisco03/disenchanter#15]
---- Minecraft Crash Report ----
// My bad.

Time: 2023-04-02 12:55:12
Description: Rendering screen

java.lang.IncompatibleClassChangeError: Expecting non-static method 'void net.minecraft.class_332.method_25302(net.minecraft.class_4587, int, int, int, int, int, int)'
	at com.glisco.disenchanter.client.DisenchanterScreen.method_2389(DisenchanterScreen.java:36)
	at net.minecraft.class_465.method_25394(class_465.java:98)
	at com.glisco.disenchanter.client.DisenchanterScreen.method_25394(DisenchanterScreen.java:42)
	at net.minecraft.class_437.method_47413(class_437.java:121)
	at net.minecraft.class_757.method_3192(class_757.java:937)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.glisco.disenchanter.client.DisenchanterScreen.method_2389(DisenchanterScreen.java:36)
	at net.minecraft.class_465.method_25394(class_465.java:98)
	at com.glisco.disenchanter.client.DisenchanterScreen.method_25394(DisenchanterScreen.java:42)
	at net.minecraft.class_437.method_47413(class_437.java:121)

-- Screen render details --
Details:
	Screen name: com.glisco.disenchanter.client.DisenchanterScreen
	Mouse location: Scaled: (320, 180). Absolute: (960.000000, 540.000000)
	Screen size: Scaled: (640, 360). Absolute: (1920, 1080). Scale factor of 3.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:937)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Sourpunch41'/137, l='ClientLevel', x=-292.34, y=64.00, z=205.15]]
	Chunk stats: 1024, 454
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,72,0), Section: (at 0,8,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 632151 game time, 964976 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:820)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, Fabric Mods, minecraft/supporteatinganimation, file/Custom Totem.zip, file/Sanguineresourcepack.zip

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1150565512 bytes (1097 MiB) / 4831838208 bytes (4608 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce RTX 2060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f15
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2802
	Graphics card #1 name: Intel(R) UHD Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x9bc4
	Graphics card #1 versionInfo: DriverVersion=31.0.101.1999
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 22364.62
	Virtual memory used (MB): 17493.43
	Swap memory total (MB): 6144.00
	Swap memory used (MB): 382.39
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		appleskin: AppleSkin 2.4.3+mc1.19.4
		architectury: Architectury 8.1.75
		armored-elytra: Armored Elytra 4.0.0+build.20
		azurelib: AzureLib 1.0.7
			com_eliotlash_mclib_mclib: mclib 20
		balm-fabric: Balm 6.0.2
		bedrockplus: Bedrock Plus Mod 1.4.1
		betterf3: BetterF3 6.0.0
		brewery: Brewery 0.3.2+1.19.4-rc2
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			net_objecthunter_exp4j: exp4j 0.4.8
			placeholder-api: Placeholder API 2.0.0-pre.4+1.19.3
			polymer-core: Polymer (Core) 0.4.0-pre.2+1.19.4-rc2
				polymer-networking: Polymer (Networking) 0.4.0-pre.2+1.19.4-rc2
			polymer-resource-pack: Polymer (Resource Pack) 0.4.0-pre.2+1.19.4-rc2
			polymer-virtual-entity: Polymer (Virtual Entity) 0.4.0-pre.2+1.19.4-rc2
				polymer-common: Polymer (Common) 0.4.0-pre.2+1.19.4-rc2
			server_translations_api: Server Translations API 2.0.0-beta.2+1.19.4-pre2
				packet_tweaker: Packet Tweaker 0.3.1+23w06a
			sgui: sgui 1.2.1+1.19.3
		cardinal-components-base: Cardinal Components API (base) 5.1.0
		cardinal-components-entity: Cardinal Components API (entities) 5.1.0
		cloth-config: Cloth Config v10 10.0.96
			cloth-basic-math: cloth-basic-math 0.6.1
		cookingforblockheads: Cooking for Blockheads 15.0.1
		culinaryconstruct: Culinary Construct 5.1.0+1.19.4
			spectrelib: SpectreLib 0.12.4+1.19.2
				com_electronwill_night-config_core: core 3.6.5
				com_electronwill_night-config_toml: toml 3.6.5
		disenchanter: Disenchanter 0.1.7+1.19.3
		eatinganimationid: Eating Animation 1.9.3
		emi: EMI 0.7.2+1.19.4
		emitrades: EMI Trades 1.1.0+mc1.19.3
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		enhanced_quarries: Enhanced Quarries 1.19.4-1.3.1
		entityculling: EntityCulling-Fabric 1.6.2-mc1.19.4
		fabric-api: Fabric API 0.76.0+1.19.4
			fabric-api-base: Fabric API Base 0.4.23+9ff28bcef4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.24+49abcf7ef4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.6+348a9c64f4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.5+e022e5d1f4
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.33+c2e6f674f4
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.14+1134c5b8f4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.25+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.4+ae0966baf4
			fabric-commands-v0: Fabric Commands (v0) 0.2.42+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.52+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.7+ae0966baf4
			fabric-convention-tags-v1: Fabric Convention Tags 1.4.0+9a7c5daaf4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.14+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.3.5+5da15ca1f4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.44+7f87f8faf4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.12+e45f7c65f4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.42+a1ccd7bff4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.51+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.32+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.16+09a3510cf4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.3+043f9acff4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.32+c477957ef4
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.30+df3654b3f4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.14+5da15ca1f4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.25+75e98211f4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.29+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.0+1ee8be40f4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.37+49abcf7ef4
			fabric-models-v0: Fabric Models (v0) 0.3.29+11ba9c3bf4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.22+ca5f59aaf4
			fabric-networking-v0: Fabric Networking (v0) 0.3.39+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.0.1+63b515f4f4
			fabric-particles-v1: Fabric Particles (v1) 1.0.22+f1e4495bf4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.6+a1ccd7bff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.1.2+a383ab97f4
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.4+81e8c576f4
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.1.0+81e8c576f4
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.37+df3654b3f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.27+afca2f3ef4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.20+f1e4495bf4
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.40+df3654b3f4
			fabric-rendering-v1: Fabric Rendering (v1) 2.1.0+8f878217f4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.0+e6c7d4eef4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.0+938a1d56f4
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.44+8c25edb4f4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.18+5da15ca1f4
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.8+75e98211f4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.0.1+9003cbe9f4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.0.2+63b515f4f4
		fabricloader: Fabric Loader 0.14.18
		fabricskyboxes: FabricSkyBoxes 0.6.5+mc1.19.4
		geckolib: Geckolib 4.1.2
		hwg: Happiness is a Warm Gun 1.4.2
		java: OpenJDK 64-Bit Server VM 17
		lambdynlights: LambDynamicLights 2.3.0+1.19.4
			pride: Pride Lib 1.2.0+1.19.4
			spruceui: SpruceUI 4.2.0+1.19.4
		lithium: Lithium 0.11.1
		mcpitanlibarch: MCPitanLib 1.5.7-1.19.4-fabric
			org_yaml_snakeyaml: snakeyaml 2.0
		minecraft: Minecraft 1.19.4
		modmenu: Mod Menu 6.1.0-rc.4
		mtr: Minecraft Transit Railway 1.19.4-3.2.1-hotfix-1
		owo: oωo 0.10.3+1.19.4
			blue_endless_jankson: jankson 1.2.2
		pfm: Paladin's Furniture 1.1.3
		phosphor: Phosphor 0.8.1
		pipeplus: PipePlus 1.19.3-0.5.1
		reborncore: Reborn Core 5.7.0
			team_reborn_energy: Energy 3.0.0
		reeses-sodium-options: Reese's Sodium Options 1.5.0+mc1.19.4-build.72
		reinfchest: Reinforced Chests 2.3.2+1.19
			reinfcore: Reinforced Core 3.0.6+1.19
		roughlyenoughitems: Roughly Enough Items 11.0.597
			error_notifier: Error Notifier 1.0.9
		sanguine_mr: Sanguine 0.3.2
		simple_pipes_dep_container: SimplePipeTest (Dependency Container) 0.10.0
			libblockattributes: LibBlockAttributes 0.13.0
				libblockattributes_core: LibBlockAttributes (Core) 0.13.0
				libblockattributes_fluids: LibBlockAttributes (Fluids) 0.13.0
				libblockattributes_items: LibBlockAttributes (Items) 0.13.0
			libmultipart: LibMultiPart 0.10.0
			libmultipart_compat: LibMultiPart (Mod Compatibility) 0.10.0
			libnetworkstack: Lib Network Stack 0.9.0
			simple_pipes: SimplePipeTest 0.10.0
		smartbrainlib: SmartBrainLib 1.9
		sodium: Sodium 0.4.10+build.24
		sodium-extra: Sodium Extra 0.4.18+mc1.19.4-build.100
			caffeineconfig: CaffeineConfig 1.1.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		sound_physics_remastered: Sound Physics Remastered 1.19.4-1.1.0
		taxfreelevels: Tax Free Levels 1.3.3
		techreborn: Tech Reborn 5.7.0
		toolleveling: ToolLeveling+ 1.19.4-1.4.4
		travelersbackpack: Traveler's Backpack 1.19.4-8.4.0
		vcinteraction: Voice Chat Interaction 1.19.4-1.0.3
			polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.4.0+1.19.4
		voicechat: Simple Voice Chat 1.19.4-2.3.28
	Launched Version: fabric-loader-0.14.18-1.19.4
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 2060/PCIe/SSE2 GL version 3.2.0 NVIDIA 528.02, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, fabric, minecraft:supporteatinganimation, file/Custom Totem.zip (incompatible), file/Sanguineresourcepack.zip (incompatible)
	Current Language: en_us
	CPU: 8x Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Sourpunch41'/137, l='ServerLevel[GOobery]', x=-292.34, y=64.00, z=205.15]]
	Data Packs: vanilla, fabric, $polymer-resources, file/armored elytra v1.0.6.zip, file/fast leaf decay v2.0.6.zip
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable

**Comment by gliscowo** [comment]
Thanks for reporting this, it has now been fixed in a [specific 1.19.4 build of the mod](https://modrinth.com/mod/disenchanter/version/L9dMNzhb)

Cheers
