### ISSUE TITLE
Amethyst Shard description not accurate, Disenchanter GUI doesn't keep items when closing it.

### ISSUE THREAD

**Issue by TheUnderTaker11** [glisco03/disenchanter#16]
1. Amethyst Shard description is not specific enough at all. Let me just put Amethyst shard description and Ender Pearl description in the same screenshot.
![image](https://user-images.githubusercontent.com/16872377/230230704-48c5f33d-0971-4ded-b957-93d03f350ec7.png)
Anyone reading this would obviously assume Ender Pearl is just a worse Amethyst shard. It needs to specify all other enchants will be lost

2. Disenchanter GUI doesn't hold items. There is 2 items you need every time you disenchant, I don't see any good reason to not make it hold the items. At least a config option or something would be nice.

**Comment by gliscowo** [comment]
While I do understand how implementing your second point could bring about some slight improvements in convenivent, it takes a non-trivial amount of implementation work to actually get this done - and for the time being I'm not particularly interested in spending said time on what is really mostly a cosmetic feature

Cheers
