### ISSUE TITLE
Crashing 1.19.2 in start (code -1)

### ISSUE THREAD

**Issue by Fompi06** [glisco03/disenchanter#17]
[crash-2023-04-10_23.45.26-client.txt](https://github.com/gliscowo/disenchanter/files/11193094/crash-2023-04-10_23.45.26-client.txt)

[latest.log](https://github.com/gliscowo/disenchanter/files/11193086/latest.log)

**Comment by Noaaan** [comment]
You are using a 1.19.3 version of Disenchanter. I believe this the reason you are crashing

**Comment by Fompi06** [comment]
Yes, that was indeed the problem. Apparently I did not notice when I downloaded from the site. Thank you!
