### ISSUE TITLE
[Fabric 1.20.1] Carriage Return symbols shows up in all Catalysts' tooltips

### ISSUE THREAD

**Issue by kingkuys2123** [glisco03/disenchanter#18]
Disenchanter 0.1.7

Minecraft 1.20.1
Fabric 0.14.22
Fabric API 0.87.0
Java 20.0.2

##

![image](https://github.com/gliscowo/disenchanter/assets/114457180/bbe6c4a7-2f7c-4ab2-b8cf-d17ea58e944b)

**Comment by Noaaan** [comment]
Java 8 on Minecraft 1.20? Are you sure about this? As of Minecraft 1.17 you need Java 17 to run the game.

**Comment by kingkuys2123** [comment]
Oh, I have Java 8, JDK 17 and JDK 20 installed on my pc. Maybe I should change the java version and uninstall the older versions. 

Edit:
Heres' the update! @Noaaan 
![image](https://github.com/gliscowo/disenchanter/assets/114457180/02977660-7c30-4d66-a56e-e95f747aac10)

**Comment by gliscowo** [comment]
Thanks for reporting this, the fix is now available in [0.1.8](https://modrinth.com/mod/disenchanter/version/b2NIHM63)
Cheers
