### ISSUE TITLE
Disenchanter doesn't check if item "breaks" after damage.

### ISSUE THREAD

**Issue by roobscoob** [glisco03/disenchanter#19]
https://github.com/gliscowo/disenchanter/blob/74c85a77e9fae610cbdd2797dce173fbc66eff6a/src/main/java/com/glisco/disenchanter/catalyst/Catalysts.java#L74C19-L74C19

This call to .damage can make item's durability negative.
If the item's durability is negative, the disenchanter shouldn't return it (broken)

**Comment by roobscoob** [comment]
also, ItemStack::damage checks for Unbreaking. Not sure if this is intentional, but doesn't really make sense given the context of this item

**Comment by gliscowo** [comment]
Hey, thanks for bringing this to my attention! I've now changed the implementation to damage the stack directly and also handle the case that it breaks. 

These changes are available in the [0.1.9+1.20.2](https://modrinth.com/mod/disenchanter/version/0.1.9+1.20.2) release
Cheers
