### ISSUE TITLE
An option to disable disenchanting without catalyst

### ISSUE THREAD

**Issue by Rad586** [glisco03/disenchanter#21]
As the title says, it's kinda unbalanced to disenchant with out catalyst, players usually get mending on a golden things due to its high enchantability, especially in modpacks. 
Also, if this feature won't be backported to 1.19.2, may I release a fork for my modpack?

**Comment by Noaaan** [comment]
If you wish to fork the mod for your pack thats within your right, as the mod is licensed under MIT.
I do want to note that mending is *not* obtainable from an Enchanting Table in a non-modded context, as it is a treasure enchantment. If this is not the case in your pack I would recommend looking through your mods, as it sounds like your players might be able to put enchantments on tools through unintentional means.

**Comment by Rad586** [comment]
Thanks for your kind suggestion! I think I said it wrong, I mean the golden things in chests.

**Comment by gliscowo** [comment]
Hey, I've now implemented this functionality in [0.1.9 for 1.20.2](https://modrinth.com/mod/disenchanter/version/0.1.9+1.20.2) - if and once you update your pack, you'll be able to use that version (or a future one)

Also, I just wanted to say that I appreciate being added to the CF project for your fork and that you link back to the original in the description - even though this should be common sense, it's apparently pretty hard for some people to do

Cheers
