### ISSUE TITLE
The item isn't craftable

### ISSUE THREAD

**Issue by ifacodes** [glisco03/disenchanter#26]
The disenchanter shows up in REI, but it isn't craftable, and the recipe does not work. 

This seems to be because the recipe format is now incorrect.

Minecraft 1.21.3
Fabric Loader 0.16.9

**Comment by gliscowo** [comment]
Thanks for bringing this to my attention, I've released a fix in [0.1.11](https://modrinth.com/mod/OQ8To4FT/version/ZcZwAedh).

I also appreciate your PR on this topic, although I have a cleaner solution which I implemented in the released version - so I'll go ahead and close that too

Cheers
